hosts:
  - https://valutac.com
auth:
  username: admin
  password: ganteng
scheduler:
  time: 5
notification:
  active: false
  email:
    sender: ""
    host: ""
    username: ""
    password: ""
    port: 5678
  telegram:
    token: ""
    target:
      -